# Generated by Django 4.1.3 on 2022-11-19 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
        ("livro", "0003_categoria_livros_categoria"),
    ]

    operations = [
        migrations.RenameField(
            model_name="livros",
            old_name="Categoria",
            new_name="categoria",
        ),
        migrations.AddField(
            model_name="livros",
            name="usuario",
            field=models.ForeignKey(
                default=15,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="usuarios.usuario",
            ),
        ),
    ]
