# Generated by Django 4.1.3 on 2022-11-19 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
        ("livro", "0004_rename_categoria_livros_categoria_livros_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livros",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="usuarios.usuario"
            ),
        ),
    ]
