# Generated by Django 4.1.3 on 2022-11-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livro", "0005_alter_livros_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livros",
            name="emprestado",
            field=models.BooleanField(default=False),
        ),
    ]
