# Generated by Django 4.1.3 on 2022-11-20 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("livro", "0007_emprestimos_categoria_usuario"),
    ]

    operations = [
        migrations.CreateModel(
            name="Emprestimo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_emprestado",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("data_emprestimo", models.DateTimeField(blank=True, null=True)),
                ("data_devolucao", models.DateTimeField(blank=True, null=True)),
                ("tempo_duracao", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Emprestimos",
        ),
        migrations.RemoveField(
            model_name="livros",
            name="data_devolucao",
        ),
        migrations.RemoveField(
            model_name="livros",
            name="data_emprestimo",
        ),
        migrations.RemoveField(
            model_name="livros",
            name="nome_emprestado",
        ),
        migrations.RemoveField(
            model_name="livros",
            name="tempo_duracao",
        ),
        migrations.AddField(
            model_name="emprestimo",
            name="livro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="livro.livros"
            ),
        ),
    ]
