# Generated by Django 4.1.3 on 2022-11-20 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
        ("livro", "0008_emprestimo_delete_emprestimos_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emprestimo",
            name="nome_emprestado_anonimo",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="emprestimo",
            name="nome_emprestado",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="usuarios.usuario",
            ),
            preserve_default=False,
        ),
    ]
