# Generated by Django 4.1.3 on 2022-11-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livro", "0010_alter_emprestimo_nome_emprestado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emprestimo",
            name="data_devolucao",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emprestimo",
            name="data_emprestimo",
            field=models.DateField(blank=True, null=True),
        ),
    ]
