# Generated by Django 4.1.3 on 2022-11-20 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("livro", "0011_alter_emprestimo_data_devolucao_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emprestimo",
            name="tempo_duracao",
        ),
    ]
