# Generated by Django 4.1.3 on 2022-11-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livro", "0012_remove_emprestimo_tempo_duracao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
    ]
