# Generated by Django 4.1.3 on 2022-11-21 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livro", "0014_emprestimo_avaliacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emprestimo",
            name="data_emprestimo",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(2022, 11, 21, 3, 29, 21, 258048),
                null=True,
            ),
        ),
    ]
