# Generated by Django 4.1.3 on 2022-11-21 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livro", "0015_alter_emprestimo_data_emprestimo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emprestimo",
            name="data_emprestimo",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 11, 21, 6, 31, 19, 993133, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
