# Generated by Django 4.1.3 on 2022-11-21 06:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("livro", "0016_alter_emprestimo_data_emprestimo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emprestimo",
            name="data_emprestimo",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
