# Generated by Django 4.1.3 on 2022-11-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livro", "0017_alter_emprestimo_data_emprestimo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emprestimo",
            name="avaliacao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("P", "Pésssimo"),
                    ("R", "Ruim"),
                    ("B", "Bom"),
                    ("O", "Ótimo"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
