# Generated by Django 4.1.3 on 2022-11-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livro", "0018_alter_emprestimo_avaliacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="livros",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="capa_livro"),
        ),
    ]
